### ISSUE TITLE
Hello, I'm also engaged in ares engine.

### ISSUE THREAD

**Issue by zhuoxxx** [huweiunique/MobileMirResourceUtil#1]
Hello, I saw the packaging and unpacking of the Ares engine resources you released. I think you should be Chinese. I want to see if you still have any ares resource files here? I can buy it here. thank you. If you see any trouble, please contact me. You can add my QQ 845271762 or email 845271762@qq.com

**Comment by huweiunique** [comment]
你好，我确实是中国人。不过我手里并没有战神引擎相关的资源，这个工具是几年前有个朋友曾经想自定义战神引擎的服务端，但是资源文件不知道如何改，我后面花了点时间分析了下格式，做了一个小工具，但是后面朋友和我也都没有再研究这块的东西，代码本着如果有人也想解析资源包可以参考下的想法放在了github上。

**Comment by zhuoxxx** [comment]
好的。谢谢您了 作者
